### ISSUE TITLE
Docs.rs fails to build docs with an Internal Compiler Error

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [rust-amplify/io-reactor#27] opened 2024-03-29 23:43 UTC
Docs for 0.5.0 are not available on docs.rs, build logs here: https://docs.rs/crate/io-reactor/0.5.0/builds/1134663

**Comment by apiraino** [comment] 2024-04-02 09:49
This is caused by https://github.com/rust-lang/rust/issues/123287

(a regression in the latest `rustc` in the beta release channel)

**Comment by dr-orlovsky** [comment] 2024-05-15 07:47
Fixed in https://docs.rs/crate/io-reactor/0.5.1

**Closed by dr-orlovsky** 2024-05-15 07:47 UTC
